version: "3.5"
services:

  memcached:
    container_name: memcached
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - default
      - development

  redis:
    container_name: redis
    build:
      context: ./backend/redis
      dockerfile: Dockerfile.redis
    environment:
      - "REDIS_DEBUG_LEVEL=notice"
      - "REDIS_SERVICE_PORT=6379"
      - "REDIS_KEEPALIVE_TIME=300"
      - "REDIS_TIMEOUT=600"
      - "REDIS_TCP_BACKLOG=255"
      - "REDIS_MAXCLIENT=1500"
      - "REDIS_MAXMEMORY=24mb"
      - "REDIS_DATABASECOUNT=8"
    ports:
      - "6379:6379"
    command: confd -backend env
    volumes:
      - redisstore:/data
    networks:
      - default
      - development

  defaultdb:
    container_name: defaultdb
    build:
      context: ./backend/mysql
      dockerfile: Dockerfile.mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    volumes:
      - ./backend/mysql/conf.d/:/etc/mysql/conf.d
      - ./backend/mysql/initdb/:/docker-entrypoint-initdb.d
      - datastore:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
      - development

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default
      - development

volumes:
  workdir:
    driver_opts:
      type: none
      device: $HOME/volumes/work
      o: bind
  datastore:
    driver_opts:
      type: none
      device: $HOME/volumes/datastore
      o: bind
  redisstore:
    driver_opts:
      type: none
      device: $HOME/volumes/redisstore
      o: bind

networks:
  development:
    external: true

